[project]
name = "minit"
version = "0.1.0"
description = "My minimal environment init"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-core>=2.18.5",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.4.0",
    "pre-commit>=4.2.0",
]
